export const globalNames = [
{"GlobalName": "ERRORS", "ClassName": ""},
{"GlobalName": "ENS.ACTIVITY.DATA.SECONDSD", "ClassName": ""},
{"GlobalName": "ENS.ACTIVITY.DATA.SECONDSI", "ClassName": ""},
{"GlobalName": "ENS.ALERTING.MANAGEDALERTD", "ClassName": ""},
{"GlobalName": "ENS.ALERTING.NOTREQUESTD", "ClassName": ""},
{"GlobalName": "ENS.RULE.LOGD", "ClassName": ""},
{"GlobalName": "ENS.UTIL.LOGD", "ClassName": ""},
{"GlobalName": "HS.FHIRMETA.STORAGE.RSRCD", "ClassName": ""},
{"GlobalName": "HS.FHIRSERVER.META", "ClassName": ""},
{"GlobalName": "SAMPLE.DBE95BC.GLOBALANALY9E3AD", "ClassName": "SAMPLE.DBEXPANSION.DATA.GLOBALANALYSISINFO.CLS"},
{"GlobalName": "SAMPLE.DBE95BC.GLOBALANALY9E3AI", "ClassName": "SAMPLE.DBEXPANSION.DATA.GLOBALANALYSISINFO.CLS"},
{"GlobalName": "SIMPLE.HUMAND", "ClassName": "SIMPLE.HUMAN.CLS"},
{"GlobalName": "SIMPLE.HUMANI", "ClassName": "SIMPLE.HUMAN.CLS"},
{"GlobalName": "Enter your own global in the search box below", "ClassName": ""}]
